//
//  MovieDetailPresenter.swift
//  Tmdb
//
//  Created by Yeşim Daşdemir on 21.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic {
    func presentMovieDetail(response: GetMovieDetail.MovieDetail.Response?)
}

final class MovieDetailPresenter: MovieDetailPresentationLogic {
    weak var viewController: MovieDetailDisplayLogic?
    
    
    private var imageWidth: String = String(describing: Int(UIScreen.main.bounds.width / 100.0) * 100)
    
    // MARK: Methods
    
    func presentMovieDetail(response: GetMovieDetail.MovieDetail.Response?) {
        
        if let response = response {
            
            let viewModel = SimpleDetailViewModel(title: response.title,
                                                  description: response.overview,
                                                  imageWidth: imageWidth,
                                                  posterPath: response.posterPath)
            viewController?.displayMovieDetail(viewModel: viewModel)
        }
    }
}
