//
//  MovieDetailModels.swift
//  Tmdb
//
//  Created by Yeşim Daşdemir on 21.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum GetMovieDetail {
    // MARK: Use cases
    
    enum MovieDetail {
        struct Request {
            
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
        }
    }
}
