//
//  MovieDetailInteractor.swift
//  Tmdb
//
//  Created by Yeşim Daşdemir on 21.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailBusinessLogic {
    func getMovieDetail()
}

protocol MovieDetailDataStore {
    var id: String? { get set }
}

final class MovieDetailInteractor: MovieDetailBusinessLogic, MovieDetailDataStore {
   
    var presenter: MovieDetailPresentationLogic?
    var worker: MovieDetailWorker?
    
    var id: String?
    
    // MARK: Do something
    
    func getMovieDetail() {
        worker = MovieDetailWorker()
        worker?.doSomeWork()
        
        let response = GetMovieDetail.MovieDetail.Response()
        presenter?.presentMovieDetail(response: response)
    }
}
