//
//  MovieDetailModels.swift
//  Tmdb
//
//  Created by Yeşim Daşdemir on 21.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum GetMovieDetail {
    
    enum MovieDetail {
        
        struct Request: Codable {
            let transactionUrl: String
            let language: String
            let selectedId: Int
            let apiKey: String
        }
        
        struct Response: Codable {
            let id: Int?
            let backdrop_path: String?
            let overview: String?
            let original_language: String?
            let title: String?
            let vote_count: Int?
        }
        
        struct ViewModel {
        }
    }
}
