//
//  MovieDetailRouter.swift
//  Tmdb
//
//  Created by Yeşim Daşdemir on 21.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MovieDetailRoutingLogic {
}

protocol MovieDetailDataPassing {
  var dataStore: MovieDetailDataStore? { get }
}

final class MovieDetailRouter: NSObject, MovieDetailRoutingLogic, MovieDetailDataPassing {
  weak var viewController: MovieDetailViewController?
  var dataStore: MovieDetailDataStore?
  
  // MARK: Routing
  
  // MARK: Navigation
  
  //func navigateToSomewhere(source: MovieDetailViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: MovieDetailDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
