//
//  MovieDetailPresenter.swift
//  Tmdb
//
//  Created by Yeşim Daşdemir on 21.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic {
    func presentMovieDetail(response: GetMovieDetail.MovieDetail.Response)
}

final class MovieDetailPresenter: MovieDetailPresentationLogic {
  weak var viewController: MovieDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentMovieDetail(response: GetMovieDetail.MovieDetail.Response) {
    viewController?.displayMovieDetail()
  }
}
