//
//  MovieListRouter.swift
//  Tmdb
//
//  Created by Yeşim Daşdemir on 21.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MovieListRoutingLogic {
    func routeToMovieDetail(selectedMovieId: Int)
}

protocol MovieListDataPassing {
    var dataStore: MovieListDataStore? { get }
}

class MovieListRouter: NSObject, MovieListRoutingLogic, MovieListDataPassing {
    weak var viewController: MovieListViewController?
    var dataStore: MovieListDataStore?
    
    // MARK: Routing
    
    func routeToMovieDetail(selectedMovieId: Int) {
        let storyboard = UIStoryboard(name: "MovieDetail", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "MovieDetail") as! MovieDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToMovieDetail(selectedMovieId: selectedMovieId, source: dataStore!, destination: &destinationDS)
        navigateToMovieDetail(source: viewController!, destination: destinationVC)
    }
    
    //   MARK: Navigation
    
    func navigateToMovieDetail(source: MovieListViewController, destination: MovieDetailViewController) {
        source.show(destination, sender: nil)
    }
    
    //   MARK: Passing data
    
    func passDataToMovieDetail(selectedMovieId: Int, source: MovieListDataStore, destination: inout MovieDetailDataStore) {
        destination.selectedMovieId = selectedMovieId
    }
}
