//
//  MovieListWorker.swift
//  Tmdb
//
//  Created by Yeşim Daşdemir on 21.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class MovieListWorker {
//    func getMovieList(request: GetMovieList.MovieList.Request, success:@escaping(responseHandler), fail:@escaping(responseHandler)) {
        
//        let url = URL(string: request.transactionUrl)
//
//        let session = URLSession.shared
//
//        if let url = url {
//            let task = session.dataTask(with: url) { (data, response, error) in
//
//                if error != nil {
//                    let alert = UIAlertController(title: "Error", message: error?.localizedDescription, preferredStyle: .alert)
//
//                    let okButton = UIAlertAction(title: "OK", style: .default, handler: nil)
//
//                    alert.addAction(okButton)
//
//                } else {
//
//                    if let data = data {
//
//                        do {
//                            let response = try JSONDecoder().decode(GetMovieList.MovieList.Response.self, from: data)
//                            DispatchQueue.main.async { [weak self] in
//                                print(response)
//                            }
//                        } catch  {
//                            print(error)
//                        }
//                    }
//                }
//            }
//            task.resume()
//        }
//    }
}
