//
//  MovieListViewController.swift
//  Tmdb
//
//  Created by Yeşim Daşdemir on 21.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieListDisplayLogic: class {
    func displayMovieList(response: GetMovieList.MovieList.Response?)
}

final class MovieListViewController: UIViewController, MovieListDisplayLogic {
    var interactor: MovieListBusinessLogic?
    var router: (NSObjectProtocol & MovieListRoutingLogic & MovieListDataPassing)?
    
    @IBOutlet weak var tableView: UITableView!
    
    let searchController = UISearchController(searchResultsController: nil)
    var movieItemList: [MovieListItem]?
    var response: GetMovieList.MovieList.Response? {
        didSet {
            guard let items = response?.results else {
                return
            }
            movieItemList = items
        }
    }
    var filteredMovies: [MovieListItem] = []
    
    var isSearchBarEmpty: Bool {
        return searchController.searchBar.text?.isEmpty ?? true
    }
    
    var isFiltering: Bool {
        return searchController.isActive && !isSearchBarEmpty
    }
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MovieListInteractor()
        let presenter = MovieListPresenter()
        let router = MovieListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        tableView.delegate = self
        tableView.dataSource = self
        registerTableViewCells()
        
        navigationItem.title = "MovieList"
        setSearchViewController()
        
        interactor?.getMovieList()
    }
    
    // MARK: Do something
    
    func displayMovieList(response: GetMovieList.MovieList.Response?) {
        self.response = response
        tableView.reloadData()
    }
    
    private func setSearchViewController() {
        searchController.searchResultsUpdater = self
        searchController.obscuresBackgroundDuringPresentation = false
        searchController.searchBar.placeholder = "Movies"
        navigationItem.searchController = searchController
        definesPresentationContext = true
    }
    
    func filterContentForSearchText(_ searchText: String,
                                    category: MovieListItem? = nil) {
        
        if let response = response, let items = response.results {
            filteredMovies = items.filter { item -> Bool in
                return (item.title?.lowercased().contains(searchText.lowercased()) ?? false)
            }
        }
        
        tableView.reloadData()
    }
    
    private func registerTableViewCells() {
        let cell = UINib(nibName: "MovieItemViewCell", bundle: nil)
        tableView.register(cell, forCellReuseIdentifier: "MovieItemViewCell")
    }
}

extension MovieListViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        if let cell = tableView.dequeueReusableCell(withIdentifier: "MovieItemViewCell") as? MovieItemViewCell {
            
            if isFiltering {
                
                 let viewModel = filteredMovies.map({ item -> SingleItemViewModel in
                    return SingleItemViewModel(title: item.title,
                                               subTitle: item.release_date,
                                               imageWidth: "200",
                                               posterPath: item.poster_path!)
                })
                
                cell.movieItemView.viewModel = viewModel
                cell.movieItemView.collectionViewDelegate = self
                
            } else {
                if let movieItemList = movieItemList {
                    
                    let viewModel = movieItemList.map({ item -> SingleItemViewModel in
                       return SingleItemViewModel(title: item.title,
                                                  subTitle: item.release_date,
                                                  imageWidth: "200",
                                                  posterPath: item.poster_path!)
                   })

                    cell.movieItemView.viewModel = viewModel
                    cell.movieItemView.collectionViewDelegate = self
                }
            }
            return cell
        }
        return UITableViewCell()
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UIScreen.main.bounds.height
    }
    
    func tableView(_ tableView: UITableView, didDeselectRowAt indexPath: IndexPath) {
        router?.routeToMovieDetail()
    }
}

extension MovieListViewController: UISearchResultsUpdating {
    func updateSearchResults(for searchController: UISearchController) {
        let searchBar = searchController.searchBar
        filterContentForSearchText(searchBar.text!)
    }
}

extension MovieListViewController: MovieItemViewProtocol {
    func didSelectRow(with id: Int) {
        router?.routeToMovieDetail()
    }
}
